#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum PropertyId {
    PropAckedTransitions,
    PropAckRequired,
    PropAction,
    PropActionText,
    PropActiveText,
    PropActiveVtSessions,
    PropAlarmValue,
    PropAlarmValues,
    PropAll,
    PropAllWritesSuccessful,
    PropApduSegmentTimeout,
    PropApduTimeout,
    PropApplicationSoftwareVersion,
    PropArchive,
    PropBias,
    PropChangeOfStateCount,
    PropChangeOfStateTime,
    PropNotificationClass,
    PropBlank1,
    PropControlledVariableReference,
    PropControlledVariableUnits,
    PropControlledVariableValue,
    PropCovIncrement,
    PropDateList,
    PropDaylightSavingsStatus,
    PropDeadband,
    PropDerivativeConstant,
    PropDerivativeConstantUnits,
    PropDescription,
    PropDescriptionOfHalt,
    PropDeviceAddressBinding,
    PropDeviceType,
    PropEffectivePeriod,
    PropElapsedActiveTime,
    PropErrorLimit,
    PropEventEnable,
    PropEventState,
    PropEventType,
    PropExceptionSchedule,
    PropFaultValues,
    PropFeedbackValue,
    PropFileAccessMethod,
    PropFileSize,
    PropFileType,
    PropFirmwareRevision,
    PropHighLimit,
    PropInactiveText,
    PropInProcess,
    PropInstanceOf,
    PropIntegralConstant,
    PropIntegralConstantUnits,
    PropIssueConfirmedNotifications,
    PropLimitEnable,
    PropListOfGroupMembers,
    PropListOfObjectPropertyReferences,
    PropListOfSessionKeys,
    PropLocalDate,
    PropLocalTime,
    PropLocation,
    PropLowLimit,
    PropManipulatedVariableReference,
    PropMaximumOutput,
    PropMaxApduLengthAccepted,
    PropMaxInfoFrames,
    PropMaxMaster,
    PropMaxPresValue,
    PropMinimumOffTime,
    PropMinimumOnTime,
    PropMinimumOutput,
    PropMinPresValue,
    PropModelName,
    PropModificationDate,
    PropNotifyType,
    PropNumberOfApduRetries,
    PropNumberOfStates,
    PropObjectIdentifier,
    PropObjectList,
    PropObjectName,
    PropObjectPropertyReference,
    PropObjectType,
    PropOptional,
    PropOutOfService,
    PropOutputUnits,
    PropEventParameters,
    PropPolarity,
    PropPresentValue,
    PropPriority,
    PropPriorityArray,
    PropPriorityForWriting,
    PropProcessIdentifier,
    PropProgramChange,
    PropProgramLocation,
    PropProgramState,
    PropProportionalConstant,
    PropProportionalConstantUnits,
    PropProtocolConformanceClass,
    PropProtocolObjectTypesSupported,
    PropProtocolServicesSupported,
    PropProtocolVersion,
    PropReadOnly,
    PropReasonForHalt,
    PropRecipient,
    PropRecipientList,
    PropReliability,
    PropRelinquishDefault,
    PropRequired,
    PropResolution,
    PropSegmentationSupported,
    PropSetpoint,
    PropSetpointReference,
    PropStateText,
    PropStatusFlags,
    PropSystemStatus,
    PropTimeDelay,
    PropTimeOfActiveTimeReset,
    PropTimeOfStateCountReset,
    PropTimeSynchronizationRecipients,
    PropUnits,
    PropUpdateInterval,
    PropUtcOffset,
    PropVendorIdentifier,
    PropVendorName,
    PropVtClassesSupported,
    PropWeeklySchedule,
    PropAttemptedSamples,
    PropAverageValue,
    PropBufferSize,
    PropClientCovIncrement,
    PropCovResubscriptionInterval,
    PropCurrentNotifyTime,
    PropEventTimeStamps,
    PropLogBuffer,
    PropLogDeviceObjectProperty,
    PropEnable,
    PropLogInterval,
    PropMaximumValue,
    PropMinimumValue,
    PropNotificationThreshold,
    PropPreviousNotifyTime,
    PropProtocolRevision,
    PropRecordsSinceNotification,
    PropRecordCount,
    PropStartTime,
    PropStopTime,
    PropStopWhenFull,
    PropTotalRecordCount,
    PropValidSamples,
    PropWindowInterval,
    PropWindowSamples,
    PropMaximumValueTimestamp,
    PropMinimumValueTimestamp,
    PropVarianceValue,
    PropActiveCovSubscriptions,
    PropBackupFailureTimeout,
    PropConfigurationFiles,
    PropDatabaseRevision,
    PropDirectReading,
    PropLastRestoreTime,
    PropMaintenanceRequired,
    PropMemberOf,
    PropMode,
    PropOperationExpected,
    PropSetting,
    PropSilenced,
    PropTrackingValue,
    PropZoneMembers,
    PropLifeSafetyAlarmValues,
    PropMaxSegmentsAccepted,
    PropProfileName,
    PropAutoSlaveDiscovery,
    PropManualSlaveAddressBinding,
    PropSlaveAddressBinding,
    PropSlaveProxyEnable,
    PropLastNotifyRecord,
    PropScheduleDefault,
    PropAcceptedModes,
    PropAdjustValue,
    PropCount,
    PropCountBeforeChange,
    PropCountChangeTime,
    PropCovPeriod,
    PropInputReference,
    PropLimitMonitoringInterval,
    PropLoggingObject,
    PropLoggingRecord,
    PropPrescale,
    PropPulseRate,
    PropScale,
    PropScaleFactor,
    PropUpdateTime,
    PropValueBeforeChange,
    PropValueSet,
    PropValueChangeTime,
    PropAlignIntervals,
    PropIntervalOffset,
    PropLastRestartReason,
    PropLoggingType,
    PropRestartNotificationRecipients,
    PropTimeOfDeviceRestart,
    PropTimeSynchronizationInterval,
    PropTrigger,
    PropUtcTimeSynchronizationRecipients,
    PropNodeSubtype,
    PropNodeType,
    PropStructuredObjectList,
    PropSubordinateAnnotations,
    PropSubordinateList,
    PropActualShedLevel,
    PropDutyWindow,
    PropExpectedShedLevel,
    PropFullDutyBaseline,
    PropRequestedShedLevel,
    PropShedDuration,
    PropShedLevelDescriptions,
    PropShedLevels,
    PropStateDescription,
    PropDoorAlarmState,
    PropDoorExtendedPulseTime,
    PropDoorMembers,
    PropDoorOpenTooLongTime,
    PropDoorPulseTime,
    PropDoorStatus,
    PropDoorUnlockDelayTime,
    PropLockStatus,
    PropMaskedAlarmValues,
    PropSecuredStatus,
    PropAbsenteeLimit,
    PropAccessAlarmEvents,
    PropAccessDoors,
    PropAccessEvent,
    PropAccessEventAuthenticationFactor,
    PropAccessEventCredential,
    PropAccessEventTime,
    PropAccessTransactionEvents,
    PropAccompaniment,
    PropAccompanimentTime,
    PropActivationTime,
    PropActiveAuthenticationPolicy,
    PropAssignedAccessRights,
    PropAuthenticationFactors,
    PropAuthenticationPolicyList,
    PropAuthenticationPolicyNames,
    PropAuthenticationStatus,
    PropAuthorizationMode,
    PropBelongsTo,
    PropCredentialDisable,
    PropCredentialStatus,
    PropCredentials,
    PropCredentialsInZone,
    PropDaysRemaining,
    PropEntryPoints,
    PropExitPoints,
    PropExpirationTime,
    PropExtendedTimeEnable,
    PropFailedAttemptEvents,
    PropFailedAttempts,
    PropFailedAttemptsTime,
    PropLastAccessEvent,
    PropLastAccessPoint,
    PropLastCredentialAdded,
    PropLastCredentialAddedTime,
    PropLastCredentialRemoved,
    PropLastCredentialRemovedTime,
    PropLastUseTime,
    PropLockout,
    PropLockoutRelinquishTime,
    PropMasterExemption,
    PropMaxFailedAttempts,
    PropMembers,
    PropMusterPoint,
    PropNegativeAccessRules,
    PropNumberOfAuthenticationPolicies,
    PropOccupancyCount,
    PropOccupancyCountAdjust,
    PropOccupancyCountEnable,
    PropOccupancyExemption,
    PropOccupancyLowerLimit,
    PropOccupancyLowerLimitEnforced,
    PropOccupancyState,
    PropOccupancyUpperLimit,
    PropOccupancyUpperLimitEnforced,
    PropPassbackExemption,
    PropPassbackMode,
    PropPassbackTimeout,
    PropPositiveAccessRules,
    PropReasonForDisable,
    PropSupportedFormats,
    PropSupportedFormatClasses,
    PropThreatAuthority,
    PropThreatLevel,
    PropTraceFlag,
    PropTransactionNotificationClass,
    PropUserExternalIdentifier,
    PropUserInformationReference,
    PropUserName,
    PropUserType,
    PropUsesRemaining,
    PropZoneFrom,
    PropZoneTo,
    PropAccessEventTag,
    PropGlobalIdentifier,
    PropVerificationTime,
    PropBaseDeviceSecurityPolicy,
    PropDistributionKeyRevision,
    PropDoNotHide,
    PropKeySets,
    PropLastKeyServer,
    PropNetworkAccessSecurityPolicies,
    PropPacketReorderTime,
    PropSecurityPduTimeout,
    PropSecurityTimeWindow,
    PropSupportedSecurityAlgorithm,
    PropUpdateKeySetTimeout,
    PropBackupAndRestoreState,
    PropBackupPreparationTime,
    PropRestoreCompletionTime,
    PropRestorePreparationTime,
    PropBitMask,
    PropBitText,
    PropIsUtc,
    PropGroupMembers,
    PropGroupMemberNames,
    PropMemberStatusFlags,
    PropRequestedUpdateInterval,
    PropCovuPeriod,
    PropCovuRecipients,
    PropEventMessageTexts,
    PropEventMessageTextsConfig,
    PropEventDetectionEnable,
    PropEventAlgorithmInhibit,
    PropEventAlgorithmInhibitRef,
    PropTimeDelayNormal,
    PropReliabilityEvaluationInhibit,
    PropFaultParameters,
    PropFaultType,
    PropLocalForwardingOnly,
    PropProcessIdentifierFilter,
    PropSubscribedRecipients,
    PropPortFilter,
    PropAuthorizationExemptions,
    PropAllowGroupDelayInhibit,
    PropChannelNumber,
    PropControlGroups,
    PropExecutionDelay,
    PropLastPriority,
    PropWriteStatus,
    PropPropertyList,
    PropSerialNumber,
    PropBlinkWarnEnable,
    PropDefaultFadeTime,
    PropDefaultRampRate,
    PropDefaultStepIncrement,
    PropEgressTime,
    PropInProgress,
    PropInstantaneousPower,
    PropLightingCommand,
    PropLightingCommandDefaultPriority,
    PropMaxActualValue,
    PropMinActualValue,
    PropPower,
    PropTransition,
    PropEgressActive,
    PropInterfaceValue,
    PropFaultHighLimit,
    PropFaultLowLimit,
    PropLowDiffLimit,
    PropStrikeCount,
    PropTimeOfStrikeCountReset,
    PropDefaultTimeout,
    PropInitialTimeout,
    PropLastStateChange,
    PropStateChangeValues,
    PropTimerRunning,
    PropTimerState,
    PropApduLength,
    PropIpAddress,
    PropIpDefaultGateway,
    PropIpDhcpEnable,
    PropIpDhcpLeaseTime,
    PropIpDhcpLeaseTimeRemaining,
    PropIpDhcpServer,
    PropIpDnsServer,
    PropBacnetIpGlobalAddress,
    PropBacnetIpMode,
    PropBacnetIpMulticastAddress,
    PropBacnetIpNatTraversal,
    PropIpSubnetMask,
    PropBacnetIpUdpPort,
    PropBbmdAcceptFdRegistrations,
    PropBbmdBroadcastDistributionTable,
    PropBbmdForeignDeviceTable,
    PropChangesPending,
    PropCommand,
    PropFdBbmdAddress,
    PropFdSubscriptionLifetime,
    PropLinkSpeed,
    PropLinkSpeeds,
    PropLinkSpeedAutonegotiate,
    PropMacAddress,
    PropNetworkInterfaceName,
    PropNetworkNumber,
    PropNetworkNumberQuality,
    PropNetworkType,
    PropRoutingTable,
    PropVirtualMacAddressTable,
    PropCommandTimeArray,
    PropCurrentCommandPriority,
    PropLastCommandTime,
    PropValueSource,
    PropValueSourceArray,
    PropBacnetIpv6Mode,
    PropIpv6Address,
    PropIpv6PrefixLength,
    PropBacnetIpv6UdpPort,
    PropIpv6DefaultGateway,
    PropBacnetIpv6MulticastAddress,
    PropIpv6DnsServer,
    PropIpv6AutoAddressingEnable,
    PropIpv6DhcpLeaseTime,
    PropIpv6DhcpLeaseTimeRemaining,
    PropIpv6DhcpServer,
    PropIpv6ZoneIndex,
    PropAssignedLandingCalls,
    PropCarAssignedDirection,
    PropCarDoorCommand,
    PropCarDoorStatus,
    PropCarDoorText,
    PropCarDoorZone,
    PropCarDriveStatus,
    PropCarLoad,
    PropCarLoadUnits,
    PropCarMode,
    PropCarMovingDirection,
    PropCarPosition,
    PropElevatorGroup,
    PropEnergyMeter,
    PropEnergyMeterRef,
    PropEscalatorMode,
    PropFaultSignals,
    PropFloorText,
    PropGroupId,
    PropGroupMode,
    PropHigherDeck,
    PropInstallationId,
    PropLandingCalls,
    PropLandingCallControl,
    PropLandingDoorStatus,
    PropLowerDeck,
    PropMachineRoomId,
    PropMakingCarCall,
    PropNextStoppingFloor,
    PropOperationDirection,
    PropPassengerAlarm,
    PropPowerMode,
    PropRegisteredCarCall,
    PropActiveCovMultipleSubscriptions,
    PropProtocolLevel,
    PropReferencePort,
    PropDeployedProfileLocation,
    PropProfileLocation,
    PropTags,
    PropSubordinateNodeTypes,
    PropSubordinateTags,
    PropSubordinateRelationships,
    PropDefaultSubordinateRelationship,
    PropRepresents,
    PropReserved(u32),
    PropVendorSpecific(u32),
}

impl PropertyId {
    pub fn as_u32(&self) -> u32 {
        match self {
            Self::PropAckedTransitions => 0,
            Self::PropAckRequired => 1,
            Self::PropAction => 2,
            Self::PropActionText => 3,
            Self::PropActiveText => 4,
            Self::PropActiveVtSessions => 5,
            Self::PropAlarmValue => 6,
            Self::PropAlarmValues => 7,
            Self::PropAll => 8,
            Self::PropAllWritesSuccessful => 9,
            Self::PropApduSegmentTimeout => 10,
            Self::PropApduTimeout => 11,
            Self::PropApplicationSoftwareVersion => 12,
            Self::PropArchive => 13,
            Self::PropBias => 14,
            Self::PropChangeOfStateCount => 15,
            Self::PropChangeOfStateTime => 16,
            Self::PropNotificationClass => 17,
            Self::PropBlank1 => 18,
            Self::PropControlledVariableReference => 19,
            Self::PropControlledVariableUnits => 20,
            Self::PropControlledVariableValue => 21,
            Self::PropCovIncrement => 22,
            Self::PropDateList => 23,
            Self::PropDaylightSavingsStatus => 24,
            Self::PropDeadband => 25,
            Self::PropDerivativeConstant => 26,
            Self::PropDerivativeConstantUnits => 27,
            Self::PropDescription => 28,
            Self::PropDescriptionOfHalt => 29,
            Self::PropDeviceAddressBinding => 30,
            Self::PropDeviceType => 31,
            Self::PropEffectivePeriod => 32,
            Self::PropElapsedActiveTime => 33,
            Self::PropErrorLimit => 34,
            Self::PropEventEnable => 35,
            Self::PropEventState => 36,
            Self::PropEventType => 37,
            Self::PropExceptionSchedule => 38,
            Self::PropFaultValues => 39,
            Self::PropFeedbackValue => 40,
            Self::PropFileAccessMethod => 41,
            Self::PropFileSize => 42,
            Self::PropFileType => 43,
            Self::PropFirmwareRevision => 44,
            Self::PropHighLimit => 45,
            Self::PropInactiveText => 46,
            Self::PropInProcess => 47,
            Self::PropInstanceOf => 48,
            Self::PropIntegralConstant => 49,
            Self::PropIntegralConstantUnits => 50,
            Self::PropIssueConfirmedNotifications => 51,
            Self::PropLimitEnable => 52,
            Self::PropListOfGroupMembers => 53,
            Self::PropListOfObjectPropertyReferences => 54,
            Self::PropListOfSessionKeys => 55,
            Self::PropLocalDate => 56,
            Self::PropLocalTime => 57,
            Self::PropLocation => 58,
            Self::PropLowLimit => 59,
            Self::PropManipulatedVariableReference => 60,
            Self::PropMaximumOutput => 61,
            Self::PropMaxApduLengthAccepted => 62,
            Self::PropMaxInfoFrames => 63,
            Self::PropMaxMaster => 64,
            Self::PropMaxPresValue => 65,
            Self::PropMinimumOffTime => 66,
            Self::PropMinimumOnTime => 67,
            Self::PropMinimumOutput => 68,
            Self::PropMinPresValue => 69,
            Self::PropModelName => 70,
            Self::PropModificationDate => 71,
            Self::PropNotifyType => 72,
            Self::PropNumberOfApduRetries => 73,
            Self::PropNumberOfStates => 74,
            Self::PropObjectIdentifier => 75,
            Self::PropObjectList => 76,
            Self::PropObjectName => 77,
            Self::PropObjectPropertyReference => 78,
            Self::PropObjectType => 79,
            Self::PropOptional => 80,
            Self::PropOutOfService => 81,
            Self::PropOutputUnits => 82,
            Self::PropEventParameters => 83,
            Self::PropPolarity => 84,
            Self::PropPresentValue => 85,
            Self::PropPriority => 86,
            Self::PropPriorityArray => 87,
            Self::PropPriorityForWriting => 88,
            Self::PropProcessIdentifier => 89,
            Self::PropProgramChange => 90,
            Self::PropProgramLocation => 91,
            Self::PropProgramState => 92,
            Self::PropProportionalConstant => 93,
            Self::PropProportionalConstantUnits => 94,
            Self::PropProtocolConformanceClass => 95,
            Self::PropProtocolObjectTypesSupported => 96,
            Self::PropProtocolServicesSupported => 97,
            Self::PropProtocolVersion => 98,
            Self::PropReadOnly => 99,
            Self::PropReasonForHalt => 100,
            Self::PropRecipient => 101,
            Self::PropRecipientList => 102,
            Self::PropReliability => 103,
            Self::PropRelinquishDefault => 104,
            Self::PropRequired => 105,
            Self::PropResolution => 106,
            Self::PropSegmentationSupported => 107,
            Self::PropSetpoint => 108,
            Self::PropSetpointReference => 109,
            Self::PropStateText => 110,
            Self::PropStatusFlags => 111,
            Self::PropSystemStatus => 112,
            Self::PropTimeDelay => 113,
            Self::PropTimeOfActiveTimeReset => 114,
            Self::PropTimeOfStateCountReset => 115,
            Self::PropTimeSynchronizationRecipients => 116,
            Self::PropUnits => 117,
            Self::PropUpdateInterval => 118,
            Self::PropUtcOffset => 119,
            Self::PropVendorIdentifier => 120,
            Self::PropVendorName => 121,
            Self::PropVtClassesSupported => 122,
            Self::PropWeeklySchedule => 123,
            Self::PropAttemptedSamples => 124,
            Self::PropAverageValue => 125,
            Self::PropBufferSize => 126,
            Self::PropClientCovIncrement => 127,
            Self::PropCovResubscriptionInterval => 128,
            Self::PropCurrentNotifyTime => 129,
            Self::PropEventTimeStamps => 130,
            Self::PropLogBuffer => 131,
            Self::PropLogDeviceObjectProperty => 132,
            Self::PropEnable => 133,
            Self::PropLogInterval => 134,
            Self::PropMaximumValue => 135,
            Self::PropMinimumValue => 136,
            Self::PropNotificationThreshold => 137,
            Self::PropPreviousNotifyTime => 138,
            Self::PropProtocolRevision => 139,
            Self::PropRecordsSinceNotification => 140,
            Self::PropRecordCount => 141,
            Self::PropStartTime => 142,
            Self::PropStopTime => 143,
            Self::PropStopWhenFull => 144,
            Self::PropTotalRecordCount => 145,
            Self::PropValidSamples => 146,
            Self::PropWindowInterval => 147,
            Self::PropWindowSamples => 148,
            Self::PropMaximumValueTimestamp => 149,
            Self::PropMinimumValueTimestamp => 150,
            Self::PropVarianceValue => 151,
            Self::PropActiveCovSubscriptions => 152,
            Self::PropBackupFailureTimeout => 153,
            Self::PropConfigurationFiles => 154,
            Self::PropDatabaseRevision => 155,
            Self::PropDirectReading => 156,
            Self::PropLastRestoreTime => 157,
            Self::PropMaintenanceRequired => 158,
            Self::PropMemberOf => 159,
            Self::PropMode => 160,
            Self::PropOperationExpected => 161,
            Self::PropSetting => 162,
            Self::PropSilenced => 163,
            Self::PropTrackingValue => 164,
            Self::PropZoneMembers => 165,
            Self::PropLifeSafetyAlarmValues => 166,
            Self::PropMaxSegmentsAccepted => 167,
            Self::PropProfileName => 168,
            Self::PropAutoSlaveDiscovery => 169,
            Self::PropManualSlaveAddressBinding => 170,
            Self::PropSlaveAddressBinding => 171,
            Self::PropSlaveProxyEnable => 172,
            Self::PropLastNotifyRecord => 173,
            Self::PropScheduleDefault => 174,
            Self::PropAcceptedModes => 175,
            Self::PropAdjustValue => 176,
            Self::PropCount => 177,
            Self::PropCountBeforeChange => 178,
            Self::PropCountChangeTime => 179,
            Self::PropCovPeriod => 180,
            Self::PropInputReference => 181,
            Self::PropLimitMonitoringInterval => 182,
            Self::PropLoggingObject => 183,
            Self::PropLoggingRecord => 184,
            Self::PropPrescale => 185,
            Self::PropPulseRate => 186,
            Self::PropScale => 187,
            Self::PropScaleFactor => 188,
            Self::PropUpdateTime => 189,
            Self::PropValueBeforeChange => 190,
            Self::PropValueSet => 191,
            Self::PropValueChangeTime => 192,
            Self::PropAlignIntervals => 193,
            Self::PropIntervalOffset => 195,
            Self::PropLastRestartReason => 196,
            Self::PropLoggingType => 197,
            Self::PropRestartNotificationRecipients => 202,
            Self::PropTimeOfDeviceRestart => 203,
            Self::PropTimeSynchronizationInterval => 204,
            Self::PropTrigger => 205,
            Self::PropUtcTimeSynchronizationRecipients => 206,
            Self::PropNodeSubtype => 207,
            Self::PropNodeType => 208,
            Self::PropStructuredObjectList => 209,
            Self::PropSubordinateAnnotations => 210,
            Self::PropSubordinateList => 211,
            Self::PropActualShedLevel => 212,
            Self::PropDutyWindow => 213,
            Self::PropExpectedShedLevel => 214,
            Self::PropFullDutyBaseline => 215,
            Self::PropRequestedShedLevel => 218,
            Self::PropShedDuration => 219,
            Self::PropShedLevelDescriptions => 220,
            Self::PropShedLevels => 221,
            Self::PropStateDescription => 222,
            Self::PropDoorAlarmState => 226,
            Self::PropDoorExtendedPulseTime => 227,
            Self::PropDoorMembers => 228,
            Self::PropDoorOpenTooLongTime => 229,
            Self::PropDoorPulseTime => 230,
            Self::PropDoorStatus => 231,
            Self::PropDoorUnlockDelayTime => 232,
            Self::PropLockStatus => 233,
            Self::PropMaskedAlarmValues => 234,
            Self::PropSecuredStatus => 235,
            Self::PropAbsenteeLimit => 244,
            Self::PropAccessAlarmEvents => 245,
            Self::PropAccessDoors => 246,
            Self::PropAccessEvent => 247,
            Self::PropAccessEventAuthenticationFactor => 248,
            Self::PropAccessEventCredential => 249,
            Self::PropAccessEventTime => 250,
            Self::PropAccessTransactionEvents => 251,
            Self::PropAccompaniment => 252,
            Self::PropAccompanimentTime => 253,
            Self::PropActivationTime => 254,
            Self::PropActiveAuthenticationPolicy => 255,
            Self::PropAssignedAccessRights => 256,
            Self::PropAuthenticationFactors => 257,
            Self::PropAuthenticationPolicyList => 258,
            Self::PropAuthenticationPolicyNames => 259,
            Self::PropAuthenticationStatus => 260,
            Self::PropAuthorizationMode => 261,
            Self::PropBelongsTo => 262,
            Self::PropCredentialDisable => 263,
            Self::PropCredentialStatus => 264,
            Self::PropCredentials => 265,
            Self::PropCredentialsInZone => 266,
            Self::PropDaysRemaining => 267,
            Self::PropEntryPoints => 268,
            Self::PropExitPoints => 269,
            Self::PropExpirationTime => 270,
            Self::PropExtendedTimeEnable => 271,
            Self::PropFailedAttemptEvents => 272,
            Self::PropFailedAttempts => 273,
            Self::PropFailedAttemptsTime => 274,
            Self::PropLastAccessEvent => 275,
            Self::PropLastAccessPoint => 276,
            Self::PropLastCredentialAdded => 277,
            Self::PropLastCredentialAddedTime => 278,
            Self::PropLastCredentialRemoved => 279,
            Self::PropLastCredentialRemovedTime => 280,
            Self::PropLastUseTime => 281,
            Self::PropLockout => 282,
            Self::PropLockoutRelinquishTime => 283,
            Self::PropMasterExemption => 284,
            Self::PropMaxFailedAttempts => 285,
            Self::PropMembers => 286,
            Self::PropMusterPoint => 287,
            Self::PropNegativeAccessRules => 288,
            Self::PropNumberOfAuthenticationPolicies => 289,
            Self::PropOccupancyCount => 290,
            Self::PropOccupancyCountAdjust => 291,
            Self::PropOccupancyCountEnable => 292,
            Self::PropOccupancyExemption => 293,
            Self::PropOccupancyLowerLimit => 294,
            Self::PropOccupancyLowerLimitEnforced => 295,
            Self::PropOccupancyState => 296,
            Self::PropOccupancyUpperLimit => 297,
            Self::PropOccupancyUpperLimitEnforced => 298,
            Self::PropPassbackExemption => 299,
            Self::PropPassbackMode => 300,
            Self::PropPassbackTimeout => 301,
            Self::PropPositiveAccessRules => 302,
            Self::PropReasonForDisable => 303,
            Self::PropSupportedFormats => 304,
            Self::PropSupportedFormatClasses => 305,
            Self::PropThreatAuthority => 306,
            Self::PropThreatLevel => 307,
            Self::PropTraceFlag => 308,
            Self::PropTransactionNotificationClass => 309,
            Self::PropUserExternalIdentifier => 310,
            Self::PropUserInformationReference => 311,
            Self::PropUserName => 317,
            Self::PropUserType => 318,
            Self::PropUsesRemaining => 319,
            Self::PropZoneFrom => 320,
            Self::PropZoneTo => 321,
            Self::PropAccessEventTag => 322,
            Self::PropGlobalIdentifier => 323,
            Self::PropVerificationTime => 326,
            Self::PropBaseDeviceSecurityPolicy => 327,
            Self::PropDistributionKeyRevision => 328,
            Self::PropDoNotHide => 329,
            Self::PropKeySets => 330,
            Self::PropLastKeyServer => 331,
            Self::PropNetworkAccessSecurityPolicies => 332,
            Self::PropPacketReorderTime => 333,
            Self::PropSecurityPduTimeout => 334,
            Self::PropSecurityTimeWindow => 335,
            Self::PropSupportedSecurityAlgorithm => 336,
            Self::PropUpdateKeySetTimeout => 337,
            Self::PropBackupAndRestoreState => 338,
            Self::PropBackupPreparationTime => 339,
            Self::PropRestoreCompletionTime => 340,
            Self::PropRestorePreparationTime => 341,
            Self::PropBitMask => 342,
            Self::PropBitText => 343,
            Self::PropIsUtc => 344,
            Self::PropGroupMembers => 345,
            Self::PropGroupMemberNames => 346,
            Self::PropMemberStatusFlags => 347,
            Self::PropRequestedUpdateInterval => 348,
            Self::PropCovuPeriod => 349,
            Self::PropCovuRecipients => 350,
            Self::PropEventMessageTexts => 351,
            Self::PropEventMessageTextsConfig => 352,
            Self::PropEventDetectionEnable => 353,
            Self::PropEventAlgorithmInhibit => 354,
            Self::PropEventAlgorithmInhibitRef => 355,
            Self::PropTimeDelayNormal => 356,
            Self::PropReliabilityEvaluationInhibit => 357,
            Self::PropFaultParameters => 358,
            Self::PropFaultType => 359,
            Self::PropLocalForwardingOnly => 360,
            Self::PropProcessIdentifierFilter => 361,
            Self::PropSubscribedRecipients => 362,
            Self::PropPortFilter => 363,
            Self::PropAuthorizationExemptions => 364,
            Self::PropAllowGroupDelayInhibit => 365,
            Self::PropChannelNumber => 366,
            Self::PropControlGroups => 367,
            Self::PropExecutionDelay => 368,
            Self::PropLastPriority => 369,
            Self::PropWriteStatus => 370,
            Self::PropPropertyList => 371,
            Self::PropSerialNumber => 372,
            Self::PropBlinkWarnEnable => 373,
            Self::PropDefaultFadeTime => 374,
            Self::PropDefaultRampRate => 375,
            Self::PropDefaultStepIncrement => 376,
            Self::PropEgressTime => 377,
            Self::PropInProgress => 378,
            Self::PropInstantaneousPower => 379,
            Self::PropLightingCommand => 380,
            Self::PropLightingCommandDefaultPriority => 381,
            Self::PropMaxActualValue => 382,
            Self::PropMinActualValue => 383,
            Self::PropPower => 384,
            Self::PropTransition => 385,
            Self::PropEgressActive => 386,
            Self::PropInterfaceValue => 387,
            Self::PropFaultHighLimit => 388,
            Self::PropFaultLowLimit => 389,
            Self::PropLowDiffLimit => 390,
            Self::PropStrikeCount => 391,
            Self::PropTimeOfStrikeCountReset => 392,
            Self::PropDefaultTimeout => 393,
            Self::PropInitialTimeout => 394,
            Self::PropLastStateChange => 395,
            Self::PropStateChangeValues => 396,
            Self::PropTimerRunning => 397,
            Self::PropTimerState => 398,
            Self::PropApduLength => 399,
            Self::PropIpAddress => 400,
            Self::PropIpDefaultGateway => 401,
            Self::PropIpDhcpEnable => 402,
            Self::PropIpDhcpLeaseTime => 403,
            Self::PropIpDhcpLeaseTimeRemaining => 404,
            Self::PropIpDhcpServer => 405,
            Self::PropIpDnsServer => 406,
            Self::PropBacnetIpGlobalAddress => 407,
            Self::PropBacnetIpMode => 408,
            Self::PropBacnetIpMulticastAddress => 409,
            Self::PropBacnetIpNatTraversal => 410,
            Self::PropIpSubnetMask => 411,
            Self::PropBacnetIpUdpPort => 412,
            Self::PropBbmdAcceptFdRegistrations => 413,
            Self::PropBbmdBroadcastDistributionTable => 414,
            Self::PropBbmdForeignDeviceTable => 415,
            Self::PropChangesPending => 416,
            Self::PropCommand => 417,
            Self::PropFdBbmdAddress => 418,
            Self::PropFdSubscriptionLifetime => 419,
            Self::PropLinkSpeed => 420,
            Self::PropLinkSpeeds => 421,
            Self::PropLinkSpeedAutonegotiate => 422,
            Self::PropMacAddress => 423,
            Self::PropNetworkInterfaceName => 424,
            Self::PropNetworkNumber => 425,
            Self::PropNetworkNumberQuality => 426,
            Self::PropNetworkType => 427,
            Self::PropRoutingTable => 428,
            Self::PropVirtualMacAddressTable => 429,
            Self::PropCommandTimeArray => 430,
            Self::PropCurrentCommandPriority => 431,
            Self::PropLastCommandTime => 432,
            Self::PropValueSource => 433,
            Self::PropValueSourceArray => 434,
            Self::PropBacnetIpv6Mode => 435,
            Self::PropIpv6Address => 436,
            Self::PropIpv6PrefixLength => 437,
            Self::PropBacnetIpv6UdpPort => 438,
            Self::PropIpv6DefaultGateway => 439,
            Self::PropBacnetIpv6MulticastAddress => 440,
            Self::PropIpv6DnsServer => 441,
            Self::PropIpv6AutoAddressingEnable => 442,
            Self::PropIpv6DhcpLeaseTime => 443,
            Self::PropIpv6DhcpLeaseTimeRemaining => 444,
            Self::PropIpv6DhcpServer => 445,
            Self::PropIpv6ZoneIndex => 446,
            Self::PropAssignedLandingCalls => 447,
            Self::PropCarAssignedDirection => 448,
            Self::PropCarDoorCommand => 449,
            Self::PropCarDoorStatus => 450,
            Self::PropCarDoorText => 451,
            Self::PropCarDoorZone => 452,
            Self::PropCarDriveStatus => 453,
            Self::PropCarLoad => 454,
            Self::PropCarLoadUnits => 455,
            Self::PropCarMode => 456,
            Self::PropCarMovingDirection => 457,
            Self::PropCarPosition => 458,
            Self::PropElevatorGroup => 459,
            Self::PropEnergyMeter => 460,
            Self::PropEnergyMeterRef => 461,
            Self::PropEscalatorMode => 462,
            Self::PropFaultSignals => 463,
            Self::PropFloorText => 464,
            Self::PropGroupId => 465,
            Self::PropGroupMode => 467,
            Self::PropHigherDeck => 468,
            Self::PropInstallationId => 469,
            Self::PropLandingCalls => 470,
            Self::PropLandingCallControl => 471,
            Self::PropLandingDoorStatus => 472,
            Self::PropLowerDeck => 473,
            Self::PropMachineRoomId => 474,
            Self::PropMakingCarCall => 475,
            Self::PropNextStoppingFloor => 476,
            Self::PropOperationDirection => 477,
            Self::PropPassengerAlarm => 478,
            Self::PropPowerMode => 479,
            Self::PropRegisteredCarCall => 480,
            Self::PropActiveCovMultipleSubscriptions => 481,
            Self::PropProtocolLevel => 482,
            Self::PropReferencePort => 483,
            Self::PropDeployedProfileLocation => 484,
            Self::PropProfileLocation => 485,
            Self::PropTags => 486,
            Self::PropSubordinateNodeTypes => 487,
            Self::PropSubordinateTags => 488,
            Self::PropSubordinateRelationships => 489,
            Self::PropDefaultSubordinateRelationship => 490,
            Self::PropRepresents => 491,
            Self::PropReserved(value) => *value,
            Self::PropVendorSpecific(value) => *value,
        }
    }
}

impl From<u32> for PropertyId {
    fn from(value: u32) -> Self {
        match value {
            0 => Self::PropAckedTransitions,
            1 => Self::PropAckRequired,
            2 => Self::PropAction,
            3 => Self::PropActionText,
            4 => Self::PropActiveText,
            5 => Self::PropActiveVtSessions,
            6 => Self::PropAlarmValue,
            7 => Self::PropAlarmValues,
            8 => Self::PropAll,
            9 => Self::PropAllWritesSuccessful,
            10 => Self::PropApduSegmentTimeout,
            11 => Self::PropApduTimeout,
            12 => Self::PropApplicationSoftwareVersion,
            13 => Self::PropArchive,
            14 => Self::PropBias,
            15 => Self::PropChangeOfStateCount,
            16 => Self::PropChangeOfStateTime,
            17 => Self::PropNotificationClass,
            18 => Self::PropBlank1,
            19 => Self::PropControlledVariableReference,
            20 => Self::PropControlledVariableUnits,
            21 => Self::PropControlledVariableValue,
            22 => Self::PropCovIncrement,
            23 => Self::PropDateList,
            24 => Self::PropDaylightSavingsStatus,
            25 => Self::PropDeadband,
            26 => Self::PropDerivativeConstant,
            27 => Self::PropDerivativeConstantUnits,
            28 => Self::PropDescription,
            29 => Self::PropDescriptionOfHalt,
            30 => Self::PropDeviceAddressBinding,
            31 => Self::PropDeviceType,
            32 => Self::PropEffectivePeriod,
            33 => Self::PropElapsedActiveTime,
            34 => Self::PropErrorLimit,
            35 => Self::PropEventEnable,
            36 => Self::PropEventState,
            37 => Self::PropEventType,
            38 => Self::PropExceptionSchedule,
            39 => Self::PropFaultValues,
            40 => Self::PropFeedbackValue,
            41 => Self::PropFileAccessMethod,
            42 => Self::PropFileSize,
            43 => Self::PropFileType,
            44 => Self::PropFirmwareRevision,
            45 => Self::PropHighLimit,
            46 => Self::PropInactiveText,
            47 => Self::PropInProcess,
            48 => Self::PropInstanceOf,
            49 => Self::PropIntegralConstant,
            50 => Self::PropIntegralConstantUnits,
            51 => Self::PropIssueConfirmedNotifications,
            52 => Self::PropLimitEnable,
            53 => Self::PropListOfGroupMembers,
            54 => Self::PropListOfObjectPropertyReferences,
            55 => Self::PropListOfSessionKeys,
            56 => Self::PropLocalDate,
            57 => Self::PropLocalTime,
            58 => Self::PropLocation,
            59 => Self::PropLowLimit,
            60 => Self::PropManipulatedVariableReference,
            61 => Self::PropMaximumOutput,
            62 => Self::PropMaxApduLengthAccepted,
            63 => Self::PropMaxInfoFrames,
            64 => Self::PropMaxMaster,
            65 => Self::PropMaxPresValue,
            66 => Self::PropMinimumOffTime,
            67 => Self::PropMinimumOnTime,
            68 => Self::PropMinimumOutput,
            69 => Self::PropMinPresValue,
            70 => Self::PropModelName,
            71 => Self::PropModificationDate,
            72 => Self::PropNotifyType,
            73 => Self::PropNumberOfApduRetries,
            74 => Self::PropNumberOfStates,
            75 => Self::PropObjectIdentifier,
            76 => Self::PropObjectList,
            77 => Self::PropObjectName,
            78 => Self::PropObjectPropertyReference,
            79 => Self::PropObjectType,
            80 => Self::PropOptional,
            81 => Self::PropOutOfService,
            82 => Self::PropOutputUnits,
            83 => Self::PropEventParameters,
            84 => Self::PropPolarity,
            85 => Self::PropPresentValue,
            86 => Self::PropPriority,
            87 => Self::PropPriorityArray,
            88 => Self::PropPriorityForWriting,
            89 => Self::PropProcessIdentifier,
            90 => Self::PropProgramChange,
            91 => Self::PropProgramLocation,
            92 => Self::PropProgramState,
            93 => Self::PropProportionalConstant,
            94 => Self::PropProportionalConstantUnits,
            95 => Self::PropProtocolConformanceClass,
            96 => Self::PropProtocolObjectTypesSupported,
            97 => Self::PropProtocolServicesSupported,
            98 => Self::PropProtocolVersion,
            99 => Self::PropReadOnly,
            100 => Self::PropReasonForHalt,
            101 => Self::PropRecipient,
            102 => Self::PropRecipientList,
            103 => Self::PropReliability,
            104 => Self::PropRelinquishDefault,
            105 => Self::PropRequired,
            106 => Self::PropResolution,
            107 => Self::PropSegmentationSupported,
            108 => Self::PropSetpoint,
            109 => Self::PropSetpointReference,
            110 => Self::PropStateText,
            111 => Self::PropStatusFlags,
            112 => Self::PropSystemStatus,
            113 => Self::PropTimeDelay,
            114 => Self::PropTimeOfActiveTimeReset,
            115 => Self::PropTimeOfStateCountReset,
            116 => Self::PropTimeSynchronizationRecipients,
            117 => Self::PropUnits,
            118 => Self::PropUpdateInterval,
            119 => Self::PropUtcOffset,
            120 => Self::PropVendorIdentifier,
            121 => Self::PropVendorName,
            122 => Self::PropVtClassesSupported,
            123 => Self::PropWeeklySchedule,
            124 => Self::PropAttemptedSamples,
            125 => Self::PropAverageValue,
            126 => Self::PropBufferSize,
            127 => Self::PropClientCovIncrement,
            128 => Self::PropCovResubscriptionInterval,
            129 => Self::PropCurrentNotifyTime,
            130 => Self::PropEventTimeStamps,
            131 => Self::PropLogBuffer,
            132 => Self::PropLogDeviceObjectProperty,
            133 => Self::PropEnable,
            134 => Self::PropLogInterval,
            135 => Self::PropMaximumValue,
            136 => Self::PropMinimumValue,
            137 => Self::PropNotificationThreshold,
            138 => Self::PropPreviousNotifyTime,
            139 => Self::PropProtocolRevision,
            140 => Self::PropRecordsSinceNotification,
            141 => Self::PropRecordCount,
            142 => Self::PropStartTime,
            143 => Self::PropStopTime,
            144 => Self::PropStopWhenFull,
            145 => Self::PropTotalRecordCount,
            146 => Self::PropValidSamples,
            147 => Self::PropWindowInterval,
            148 => Self::PropWindowSamples,
            149 => Self::PropMaximumValueTimestamp,
            150 => Self::PropMinimumValueTimestamp,
            151 => Self::PropVarianceValue,
            152 => Self::PropActiveCovSubscriptions,
            153 => Self::PropBackupFailureTimeout,
            154 => Self::PropConfigurationFiles,
            155 => Self::PropDatabaseRevision,
            156 => Self::PropDirectReading,
            157 => Self::PropLastRestoreTime,
            158 => Self::PropMaintenanceRequired,
            159 => Self::PropMemberOf,
            160 => Self::PropMode,
            161 => Self::PropOperationExpected,
            162 => Self::PropSetting,
            163 => Self::PropSilenced,
            164 => Self::PropTrackingValue,
            165 => Self::PropZoneMembers,
            166 => Self::PropLifeSafetyAlarmValues,
            167 => Self::PropMaxSegmentsAccepted,
            168 => Self::PropProfileName,
            169 => Self::PropAutoSlaveDiscovery,
            170 => Self::PropManualSlaveAddressBinding,
            171 => Self::PropSlaveAddressBinding,
            172 => Self::PropSlaveProxyEnable,
            173 => Self::PropLastNotifyRecord,
            174 => Self::PropScheduleDefault,
            175 => Self::PropAcceptedModes,
            176 => Self::PropAdjustValue,
            177 => Self::PropCount,
            178 => Self::PropCountBeforeChange,
            179 => Self::PropCountChangeTime,
            180 => Self::PropCovPeriod,
            181 => Self::PropInputReference,
            182 => Self::PropLimitMonitoringInterval,
            183 => Self::PropLoggingObject,
            184 => Self::PropLoggingRecord,
            185 => Self::PropPrescale,
            186 => Self::PropPulseRate,
            187 => Self::PropScale,
            188 => Self::PropScaleFactor,
            189 => Self::PropUpdateTime,
            190 => Self::PropValueBeforeChange,
            191 => Self::PropValueSet,
            192 => Self::PropValueChangeTime,
            193 => Self::PropAlignIntervals,
            195 => Self::PropIntervalOffset,
            196 => Self::PropLastRestartReason,
            197 => Self::PropLoggingType,
            202 => Self::PropRestartNotificationRecipients,
            203 => Self::PropTimeOfDeviceRestart,
            204 => Self::PropTimeSynchronizationInterval,
            205 => Self::PropTrigger,
            206 => Self::PropUtcTimeSynchronizationRecipients,
            207 => Self::PropNodeSubtype,
            208 => Self::PropNodeType,
            209 => Self::PropStructuredObjectList,
            210 => Self::PropSubordinateAnnotations,
            211 => Self::PropSubordinateList,
            212 => Self::PropActualShedLevel,
            213 => Self::PropDutyWindow,
            214 => Self::PropExpectedShedLevel,
            215 => Self::PropFullDutyBaseline,
            218 => Self::PropRequestedShedLevel,
            219 => Self::PropShedDuration,
            220 => Self::PropShedLevelDescriptions,
            221 => Self::PropShedLevels,
            222 => Self::PropStateDescription,
            226 => Self::PropDoorAlarmState,
            227 => Self::PropDoorExtendedPulseTime,
            228 => Self::PropDoorMembers,
            229 => Self::PropDoorOpenTooLongTime,
            230 => Self::PropDoorPulseTime,
            231 => Self::PropDoorStatus,
            232 => Self::PropDoorUnlockDelayTime,
            233 => Self::PropLockStatus,
            234 => Self::PropMaskedAlarmValues,
            235 => Self::PropSecuredStatus,
            244 => Self::PropAbsenteeLimit,
            245 => Self::PropAccessAlarmEvents,
            246 => Self::PropAccessDoors,
            247 => Self::PropAccessEvent,
            248 => Self::PropAccessEventAuthenticationFactor,
            249 => Self::PropAccessEventCredential,
            250 => Self::PropAccessEventTime,
            251 => Self::PropAccessTransactionEvents,
            252 => Self::PropAccompaniment,
            253 => Self::PropAccompanimentTime,
            254 => Self::PropActivationTime,
            255 => Self::PropActiveAuthenticationPolicy,
            256 => Self::PropAssignedAccessRights,
            257 => Self::PropAuthenticationFactors,
            258 => Self::PropAuthenticationPolicyList,
            259 => Self::PropAuthenticationPolicyNames,
            260 => Self::PropAuthenticationStatus,
            261 => Self::PropAuthorizationMode,
            262 => Self::PropBelongsTo,
            263 => Self::PropCredentialDisable,
            264 => Self::PropCredentialStatus,
            265 => Self::PropCredentials,
            266 => Self::PropCredentialsInZone,
            267 => Self::PropDaysRemaining,
            268 => Self::PropEntryPoints,
            269 => Self::PropExitPoints,
            270 => Self::PropExpirationTime,
            271 => Self::PropExtendedTimeEnable,
            272 => Self::PropFailedAttemptEvents,
            273 => Self::PropFailedAttempts,
            274 => Self::PropFailedAttemptsTime,
            275 => Self::PropLastAccessEvent,
            276 => Self::PropLastAccessPoint,
            277 => Self::PropLastCredentialAdded,
            278 => Self::PropLastCredentialAddedTime,
            279 => Self::PropLastCredentialRemoved,
            280 => Self::PropLastCredentialRemovedTime,
            281 => Self::PropLastUseTime,
            282 => Self::PropLockout,
            283 => Self::PropLockoutRelinquishTime,
            284 => Self::PropMasterExemption,
            285 => Self::PropMaxFailedAttempts,
            286 => Self::PropMembers,
            287 => Self::PropMusterPoint,
            288 => Self::PropNegativeAccessRules,
            289 => Self::PropNumberOfAuthenticationPolicies,
            290 => Self::PropOccupancyCount,
            291 => Self::PropOccupancyCountAdjust,
            292 => Self::PropOccupancyCountEnable,
            293 => Self::PropOccupancyExemption,
            294 => Self::PropOccupancyLowerLimit,
            295 => Self::PropOccupancyLowerLimitEnforced,
            296 => Self::PropOccupancyState,
            297 => Self::PropOccupancyUpperLimit,
            298 => Self::PropOccupancyUpperLimitEnforced,
            299 => Self::PropPassbackExemption,
            300 => Self::PropPassbackMode,
            301 => Self::PropPassbackTimeout,
            302 => Self::PropPositiveAccessRules,
            303 => Self::PropReasonForDisable,
            304 => Self::PropSupportedFormats,
            305 => Self::PropSupportedFormatClasses,
            306 => Self::PropThreatAuthority,
            307 => Self::PropThreatLevel,
            308 => Self::PropTraceFlag,
            309 => Self::PropTransactionNotificationClass,
            310 => Self::PropUserExternalIdentifier,
            311 => Self::PropUserInformationReference,
            317 => Self::PropUserName,
            318 => Self::PropUserType,
            319 => Self::PropUsesRemaining,
            320 => Self::PropZoneFrom,
            321 => Self::PropZoneTo,
            322 => Self::PropAccessEventTag,
            323 => Self::PropGlobalIdentifier,
            326 => Self::PropVerificationTime,
            327 => Self::PropBaseDeviceSecurityPolicy,
            328 => Self::PropDistributionKeyRevision,
            329 => Self::PropDoNotHide,
            330 => Self::PropKeySets,
            331 => Self::PropLastKeyServer,
            332 => Self::PropNetworkAccessSecurityPolicies,
            333 => Self::PropPacketReorderTime,
            334 => Self::PropSecurityPduTimeout,
            335 => Self::PropSecurityTimeWindow,
            336 => Self::PropSupportedSecurityAlgorithm,
            337 => Self::PropUpdateKeySetTimeout,
            338 => Self::PropBackupAndRestoreState,
            339 => Self::PropBackupPreparationTime,
            340 => Self::PropRestoreCompletionTime,
            341 => Self::PropRestorePreparationTime,
            342 => Self::PropBitMask,
            343 => Self::PropBitText,
            344 => Self::PropIsUtc,
            345 => Self::PropGroupMembers,
            346 => Self::PropGroupMemberNames,
            347 => Self::PropMemberStatusFlags,
            348 => Self::PropRequestedUpdateInterval,
            349 => Self::PropCovuPeriod,
            350 => Self::PropCovuRecipients,
            351 => Self::PropEventMessageTexts,
            352 => Self::PropEventMessageTextsConfig,
            353 => Self::PropEventDetectionEnable,
            354 => Self::PropEventAlgorithmInhibit,
            355 => Self::PropEventAlgorithmInhibitRef,
            356 => Self::PropTimeDelayNormal,
            357 => Self::PropReliabilityEvaluationInhibit,
            358 => Self::PropFaultParameters,
            359 => Self::PropFaultType,
            360 => Self::PropLocalForwardingOnly,
            361 => Self::PropProcessIdentifierFilter,
            362 => Self::PropSubscribedRecipients,
            363 => Self::PropPortFilter,
            364 => Self::PropAuthorizationExemptions,
            365 => Self::PropAllowGroupDelayInhibit,
            366 => Self::PropChannelNumber,
            367 => Self::PropControlGroups,
            368 => Self::PropExecutionDelay,
            369 => Self::PropLastPriority,
            370 => Self::PropWriteStatus,
            371 => Self::PropPropertyList,
            372 => Self::PropSerialNumber,
            373 => Self::PropBlinkWarnEnable,
            374 => Self::PropDefaultFadeTime,
            375 => Self::PropDefaultRampRate,
            376 => Self::PropDefaultStepIncrement,
            377 => Self::PropEgressTime,
            378 => Self::PropInProgress,
            379 => Self::PropInstantaneousPower,
            380 => Self::PropLightingCommand,
            381 => Self::PropLightingCommandDefaultPriority,
            382 => Self::PropMaxActualValue,
            383 => Self::PropMinActualValue,
            384 => Self::PropPower,
            385 => Self::PropTransition,
            386 => Self::PropEgressActive,
            387 => Self::PropInterfaceValue,
            388 => Self::PropFaultHighLimit,
            389 => Self::PropFaultLowLimit,
            390 => Self::PropLowDiffLimit,
            391 => Self::PropStrikeCount,
            392 => Self::PropTimeOfStrikeCountReset,
            393 => Self::PropDefaultTimeout,
            394 => Self::PropInitialTimeout,
            395 => Self::PropLastStateChange,
            396 => Self::PropStateChangeValues,
            397 => Self::PropTimerRunning,
            398 => Self::PropTimerState,
            399 => Self::PropApduLength,
            400 => Self::PropIpAddress,
            401 => Self::PropIpDefaultGateway,
            402 => Self::PropIpDhcpEnable,
            403 => Self::PropIpDhcpLeaseTime,
            404 => Self::PropIpDhcpLeaseTimeRemaining,
            405 => Self::PropIpDhcpServer,
            406 => Self::PropIpDnsServer,
            407 => Self::PropBacnetIpGlobalAddress,
            408 => Self::PropBacnetIpMode,
            409 => Self::PropBacnetIpMulticastAddress,
            410 => Self::PropBacnetIpNatTraversal,
            411 => Self::PropIpSubnetMask,
            412 => Self::PropBacnetIpUdpPort,
            413 => Self::PropBbmdAcceptFdRegistrations,
            414 => Self::PropBbmdBroadcastDistributionTable,
            415 => Self::PropBbmdForeignDeviceTable,
            416 => Self::PropChangesPending,
            417 => Self::PropCommand,
            418 => Self::PropFdBbmdAddress,
            419 => Self::PropFdSubscriptionLifetime,
            420 => Self::PropLinkSpeed,
            421 => Self::PropLinkSpeeds,
            422 => Self::PropLinkSpeedAutonegotiate,
            423 => Self::PropMacAddress,
            424 => Self::PropNetworkInterfaceName,
            425 => Self::PropNetworkNumber,
            426 => Self::PropNetworkNumberQuality,
            427 => Self::PropNetworkType,
            428 => Self::PropRoutingTable,
            429 => Self::PropVirtualMacAddressTable,
            430 => Self::PropCommandTimeArray,
            431 => Self::PropCurrentCommandPriority,
            432 => Self::PropLastCommandTime,
            433 => Self::PropValueSource,
            434 => Self::PropValueSourceArray,
            435 => Self::PropBacnetIpv6Mode,
            436 => Self::PropIpv6Address,
            437 => Self::PropIpv6PrefixLength,
            438 => Self::PropBacnetIpv6UdpPort,
            439 => Self::PropIpv6DefaultGateway,
            440 => Self::PropBacnetIpv6MulticastAddress,
            441 => Self::PropIpv6DnsServer,
            442 => Self::PropIpv6AutoAddressingEnable,
            443 => Self::PropIpv6DhcpLeaseTime,
            444 => Self::PropIpv6DhcpLeaseTimeRemaining,
            445 => Self::PropIpv6DhcpServer,
            446 => Self::PropIpv6ZoneIndex,
            447 => Self::PropAssignedLandingCalls,
            448 => Self::PropCarAssignedDirection,
            449 => Self::PropCarDoorCommand,
            450 => Self::PropCarDoorStatus,
            451 => Self::PropCarDoorText,
            452 => Self::PropCarDoorZone,
            453 => Self::PropCarDriveStatus,
            454 => Self::PropCarLoad,
            455 => Self::PropCarLoadUnits,
            456 => Self::PropCarMode,
            457 => Self::PropCarMovingDirection,
            458 => Self::PropCarPosition,
            459 => Self::PropElevatorGroup,
            460 => Self::PropEnergyMeter,
            461 => Self::PropEnergyMeterRef,
            462 => Self::PropEscalatorMode,
            463 => Self::PropFaultSignals,
            464 => Self::PropFloorText,
            465 => Self::PropGroupId,
            467 => Self::PropGroupMode,
            468 => Self::PropHigherDeck,
            469 => Self::PropInstallationId,
            470 => Self::PropLandingCalls,
            471 => Self::PropLandingCallControl,
            472 => Self::PropLandingDoorStatus,
            473 => Self::PropLowerDeck,
            474 => Self::PropMachineRoomId,
            475 => Self::PropMakingCarCall,
            476 => Self::PropNextStoppingFloor,
            477 => Self::PropOperationDirection,
            478 => Self::PropPassengerAlarm,
            479 => Self::PropPowerMode,
            480 => Self::PropRegisteredCarCall,
            481 => Self::PropActiveCovMultipleSubscriptions,
            482 => Self::PropProtocolLevel,
            483 => Self::PropReferencePort,
            484 => Self::PropDeployedProfileLocation,
            485 => Self::PropProfileLocation,
            486 => Self::PropTags,
            487 => Self::PropSubordinateNodeTypes,
            488 => Self::PropSubordinateTags,
            489 => Self::PropSubordinateRelationships,
            490 => Self::PropDefaultSubordinateRelationship,
            491 => Self::PropRepresents,
            492..=511 => Self::PropReserved(value),
            _ => Self::PropVendorSpecific(value),
        }
    }
}
